{% set name = "gmpyinfr_dbutils" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
    sha256: d60d8f9a20359956af3083351ce6666e3adeeeb9f120d97e2ab3c0b427627254

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win or osx]

requirements:
  host:
    - pip
    - python
    - turbodbc ==4.1.2
    - pandas >=1.0.0
    - pyarrow >=3.0.0
  run:
    - python
    - turbodbc ==4.1.2
    - pandas >=1.0.0
    - pyarrow >=3.0.0

test:
  imports:
    - gmpyinfr_dbutils

about:
  home: https://github.com/anewmanvs/gmpyinfr_dbutils
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: "Infraestrutura dbutils python de uma equipe de Ciência de Dados"

extra:
  recipe-maintainers:
    - anewmanvs
